### ISSUE TITLE
Should we support OMERO 4.4?

### ISSUE THREAD

**Issue by manics** [ome/omero-wndcharm#23]
There are several bugs in OMERO4.4 which are fixed in 5.0, most notably some graph/delete related issues. How does everyone feel about dropping support for OMERO4.4?
/cc @colettace @joshmoore

**Comment by colettace** [comment]
I have no preference. Seems like a nice carrot for 5.0 early adopters.

**Comment by manics** [comment]
After a brief team discussion this morning we've agreed to drop 4.4.

**Comment by manics** [comment]
CI jobs updated to use a OMERO-5 server
- http://ci.openmicroscopy.org/view/Consortium/job/ANALYSIS-OMERO-5.1-latest-ice34/
- http://ci.openmicroscopy.org/view/Consortium/job/ANALYSIS-OMERO-PYCHRM-merge/
- http://ci.openmicroscopy.org/view/Consortium/job/ANALYSIS-OMERO-PYCHRM-deploy/
